### ISSUE TITLE
Crash when creating a prefab of a scene with pyhsics mesh

### ISSUE THREAD

**Issue by ataulien** [GameFoundry/bsf#283]
I'm getting a crash when trying to create a prefab of a scene I made, but only if I add a physics mesh to my main world mesh. It all works fine when I don't add the collider.

This is how I add the physics mesh:
```cpp
HPhysicsMesh physicsMesh = PhysicsMesh::create(mesh->getMesh()->getCachedData(), PhysicsMeshType::Triangle);

GameObjectHandle<CMeshCollider> collider = meshSO->addComponent<CMeshCollider>();
collider->setMesh(physicsMesh);
```

Here is how I create the prefab:
```cpp
HPrefab worldPrefab = Prefab::create(worldSO);
```
... which crashes with the following callstack:
```
Thread 1 "REGoth" received signal SIGSEGV, Segmentation fault.
bs::Collider::setTransform (this=0x0, pos=..., rot=...) at /home/andre/code/bsf/Source/Foundation/bsfCore/Physics/BsCollider.cpp:23
23			mInternal->setTransform(pos, rot);
(gdb) bt
#0  bs::Collider::setTransform (this=0x0, pos=..., rot=...) at /home/andre/code/bsf/Source/Foundation/bsfCore/Physics/BsCollider.cpp:23
#1  0x00007ffff774df1c in bs::CCollider::updateTransform (this=0x55555e28fa80) at /usr/include/c++/8/bits/shared_ptr_base.h:996
#2  0x00007ffff79ef529 in bs::SceneObject::notifyTransformChanged (this=0x55555e949160, flags=flags@entry=(bs::TCF_Transform | bs::TCF_Parent)) at /usr/include/c++/8/bits/shared_ptr_base.h:996
#3  0x00007ffff79f1a33 in bs::SceneObject::_setParent (this=<optimized out>, parent=..., keepWorldTransform=keepWorldTransform@entry=false)
    at /home/andre/code/bsf/Source/Foundation/bsfCore/Scene/BsSceneObject.cpp:545
#4  0x00007ffff79f6e2a in bs::SceneObjectRTTI::onDeserializationEnded (this=0x5555595c6788, obj=0x55555e948f90, context=0x7fffffffd750)
    at /home/andre/code/bsf/Source/Foundation/bsfCore/Private/RTTI/BsSceneObjectRTTI.h:148
#5  0x00007ffff76cbc27 in bs::BinarySerializer::<lambda(bs::IReflectable*)>::operator() (__closure=<synthetic pointer>, __closure=<synthetic pointer>, object=0x55555e948f90)
    at /home/andre/code/bsf/Source/Foundation/bsfUtility/Serialization/BsBinarySerializer.cpp:520
#6  bs::BinarySerializer::decodeEntry (this=this@entry=0x7fffffffd600, data=std::shared_ptr<bs::DataStream> (use count 2, weak count 0) = {...}, dataEnd=dataEnd@entry=10220, 
    output=std::shared_ptr<bs::IReflectable> (use count 5, weak count 0) = {...}) at /home/andre/code/bsf/Source/Foundation/bsfUtility/Serialization/BsBinarySerializer.cpp:589
#7  0x00007ffff76d034f in bs::BinarySerializer::decode(std::shared_ptr<bs::DataStream> const&, unsigned int, bs::SerializationContext*, std::function<void (float)>) (this=this@entry=0x7fffffffd600, 
    data=std::shared_ptr<bs::DataStream> (use count 2, weak count 0) = {...}, dataLength=dataLength@entry=10220, context=<optimized out>, progress=...)
    at /home/andre/code/bsf/Source/Foundation/bsfUtility/Serialization/BsBinarySerializer.cpp:234
#8  0x00007ffff76c89ce in bs::MemorySerializer::decode (this=this@entry=0x7fffffffd730, buffer=buffer@entry=0x55555e1f9720 "\005", bufferSize=10220, context=context@entry=0x7fffffffd750)
    at /usr/include/c++/8/ext/atomicity.h:96
#9  0x00007ffff79f0537 in bs::SceneObject::clone (this=0x55555ac591b0, instantiate=instantiate@entry=false) at /home/andre/code/bsf/Source/Foundation/bsfCore/Scene/BsSceneObject.cpp:745
#10 0x00007ffff7a049db in bs::Prefab::initialize (this=0x55555eaff9d0, sceneObject=...) at /usr/include/c++/8/bits/shared_ptr_base.h:996
#11 0x00007ffff7a055b4 in bs::Prefab::create (sceneObject=..., isScene=isScene@entry=true) at /usr/include/c++/8/bits/shared_ptr_base.h:996
#12 0x000055555557981c in BsZenLib::ImportAndCacheZEN (zen="OldWorld.zen", vdfs=...) at /home/andre/code/REGoth-bs/lib/BsZenLib/src/ImportZEN.cpp:73
#13 0x000055555556af5f in main (argc=<optimized out>, argv=<optimized out>) at /usr/include/c++/8/bits/basic_string.h:2281

```

As you can see, `this` is zero which should be the reason for the crash. Seems like the `mInternal`-pointer of the collider is not set, and it's not checked inside that `bs::CCollider::updateTransform`...

**Comment by BearishSun** [comment]
Thanks for the detailed report. The problem should now be resolved on latest master.

**Comment by ataulien** [comment]
Works now, thanks for the quick fix!
