### ISSUE TITLE
Crash when instantiating a prefab containing a collider 

### ISSUE THREAD

**Issue by ataulien** [GameFoundry/bsf#285]
This is a follow up to the closed #283.

I now tried to save the created prefab to a file, load it and then create an instance of it, which results in a similar crash as in the other issue:

```
bs::Collider::setTransform (this=0x0, pos=..., rot=...) at /home/andre/code/bsf/Source/Foundation/bsfCore/Physics/BsCollider.cpp:23
23			mInternal->setTransform(pos, rot);
(gdb) bt
#0  bs::Collider::setTransform (this=0x0, pos=..., rot=...) at /home/andre/code/bsf/Source/Foundation/bsfCore/Physics/BsCollider.cpp:23
#1  0x00007ffff774bfec in bs::CCollider::updateTransform (this=0x55555a04b950) at /usr/include/c++/8/bits/shared_ptr_base.h:996
#2  0x00007ffff79edd19 in bs::SceneObject::notifyTransformChanged (this=0x55555d695c50, flags=(bs::TCF_Transform | bs::TCF_Parent)) at /usr/include/c++/8/bits/shared_ptr_base.h:996
#3  0x00007ffff79edcb7 in bs::SceneObject::notifyTransformChanged (this=this@entry=0x55555d695e30, flags=flags@entry=(bs::TCF_Transform | bs::TCF_Parent)) at /usr/include/c++/8/bits/shared_ptr_base.h:996
#4  0x00007ffff79f02cd in bs::SceneObject::_setParent (this=0x55555d695e30, parent=..., keepWorldTransform=<optimized out>) at /home/andre/code/bsf/Source/Foundation/bsfCore/Scene/BsSceneObject.cpp:550
#5  0x00007ffff79f03fe in bs::SceneObject::setParent (this=<optimized out>, parent=..., keepWorldTransform=<optimized out>, keepWorldTransform@entry=true)
    at /home/andre/code/bsf/Source/Foundation/bsfCore/Scene/BsSceneObject.cpp:502
#6  0x00007ffff79fd38c in bs::SceneManager::registerNewSO (this=<optimized out>, node=...) at /home/andre/code/bsf/Source/Foundation/bsfCore/Scene/BsSceneManager.h:52
#7  0x00007ffff79edc31 in bs::SceneObject::<lambda(bs::SceneObject*)>::operator() (__closure=0x7fffffffd970, __closure=0x7fffffffd970, obj=0x55555d695e30)
    at /home/andre/code/bsf/Source/Foundation/bsfCore/Scene/BsSceneObject.cpp:203
#8  std::_Function_handler<void(bs::SceneObject*), bs::SceneObject::_instantiate(bool)::<lambda(bs::SceneObject*)> >::_M_invoke (__args#0=<synthetic pointer>, __functor=...)
    at /usr/include/c++/8/bits/std_function.h:297
#9  std::function<void (bs::SceneObject*)>::operator()(bs::SceneObject*) const (__args#0=0x55555d695e30, this=0x7fffffffd970) at /usr/include/c++/8/bits/std_function.h:687
#10 bs::SceneObject::_instantiate (this=0x55555d695e30, prefabOnly=<optimized out>, prefabOnly@entry=false) at /home/andre/code/bsf/Source/Foundation/bsfCore/Scene/BsSceneObject.cpp:227
#11 0x00007ffff7a02286 in bs::Prefab::instantiate (this=<optimized out>) at /usr/include/c++/8/bits/shared_ptr_base.h:996
#12 0x000055555556e900 in main (argc=<optimized out>, argv=<optimized out>) at /usr/include/c++/8/bits/shared_ptr_base.h:996

```

**Comment by BearishSun** [comment]
Thanks, this one should now also be resolved on master (e6eaf8f656067e919e1badf83f57401439e2e18f).
