### ISSUE TITLE
Animation getState setState crash

### ISSUE THREAD

**Issue by hhyyrylainen** [GameFoundry/bsf#393]
I mentioned this on discord a while ago. But I don't think anything was done, so I'm opening an issue to track this.
It seems that getState on an animation doesn't return entirely correct data.
In the examples applying this diff causes a crash:
```diff
diff --git a/Source/SkeletalAnimation/Main.cpp b/Source/SkeletalAnimation/Main.cpp
index 3c9b87a..845f222 100644
--- a/Source/SkeletalAnimation/Main.cpp
+++ b/Source/SkeletalAnimation/Main.cpp
@@ -122,6 +122,10 @@ namespace bs
                // Start playing the animation clip we imported
                animation->play(assets.exampleAnimClip);
 
+        bs::AnimationClipState state;
+        animation->getState(assets.exampleAnimClip, state);
+        animation->setState(assets.exampleAnimClip, state);
+
```

This is the crash:
```
Thread 1 "SkeletalAnimati" received signal SIGSEGV, Segmentation fault.
0x00007ffff7a8ee03 in bs::AnimationProxy::updateTime (this=0x47f9070, clipInfos=std::vector of length 2, capacity 2 = {...})
    at /home/hhyyrylainen/Projects/bsfExamples/bsf/Source/Foundation/bsfCore/Animation/BsAnimation.cpp:635
635                AnimationState& state = layers[clipInfo.layerIdx].states[clipInfo.stateIdx];
(gdb) bt
#0  0x00007ffff7a8ee03 in bs::AnimationProxy::updateTime (this=0x47f9070, clipInfos=std::vector of length 2, capacity 2 = {...})
    at /home/hhyyrylainen/Projects/bsfExamples/bsf/Source/Foundation/bsfCore/Animation/BsAnimation.cpp:635
#1  0x00007ffff7a96c03 in bs::Animation::updateAnimProxy (this=0x474cc10, timeDelta=timeDelta@entry=0.450957984)
    at /usr/include/c++/8/bits/shared_ptr_base.h:1018
#2  0x00007ffff7a9b63c in bs::AnimationManager::update (this=0x47b5e0, async=async@entry=true)
    at /home/hhyyrylainen/Projects/bsfExamples/bsf/Source/Foundation/bsfCore/Animation/BsAnimationManager.cpp:83
#3  0x00007ffff79f7b6e in bs::CoreApplication::runMainLoop (this=0x45a960)
    at /home/hhyyrylainen/Projects/bsfExamples/bsf/Source/Foundation/bsfUtility/Utility/BsModule.h:26
#4  0x0000000000406526 in main ()
```

I would expect that calling getState, updating some property like playing or speed, and then calling setState, should not cause a crash (I had to add a workaround for using explicit layers, in my code).

**Comment by BearishSun** [comment]
Thanks for the report, this should now be resolved on latest.
